---
region: 'eu-west-2'

vpc_cidr: '10.1.0.0/16'
availability_zones:
  - "eu-west-2a"
  - "eu-west-2b"
  - "eu-west-2c"

component: 'test'
deployment_identifier: "%{hiera('seed')}"

domain_name: 'infrablocks.click'
public_zone_id: "Z08829023L5IPIQBJOX63"
private_zone_id: 'Z0211739BXR21FNN139O'

allowed_cidrs:
  - '0.0.0.0/0'
egress_cidrs:
  - '10.0.0.0/8'
  - '192.168.0.0/16'

elasticsearch_domain_name: "%{hiera('component')}-%{hiera('deployment_identifier')}"
